### ISSUE TITLE
Use Docker as a runtime environment

### ISSUE THREAD

**Issue by georgevanburgh** [luke5542/LanguageComparison#1]
Requiring everyone to download 50 separate runtimes in order to run the tests is a bit funky. Using Docker, you could download a standard execution environment for each language, and execute the benchmark within, with no performance overhead.

**Comment by luke5542** [comment]
Sounds like a good option, though I don't think it should replace the current method but rather become an alternative. That way the user can choose for themselves.

**Comment by georgevanburgh** [comment]
Agreed - I think the best route initially would be to come up with a single Docker image that contains all the runtimes/code for the user to download and play with.
