### ISSUE TITLE
Validation of inputs for each example

### ISSUE THREAD

**Issue by dan-c-underwood** [luke5542/LanguageComparison#11]
Should probably make sure that the examples validate all the inputs (more useful with timing now done inside the examples).

**Comment by luke5542** [comment]
Sounds good. I think this would make an excellent next step after we finish restructuring everything.

**Comment by luke5542** [comment]
With the restructuring complete, we might want to start adding in this validation.

**Comment by dan-c-underwood** [comment]
Following the validation for Go and the shell script, this issue is now complete.
