### ISSUE TITLE
Measure timings from within code

### ISSUE THREAD

**Issue by dan-c-underwood** [luke5542/LanguageComparison#2]
Change each example to measure time taken from within the code to minimise the impact of overheads, especially for setup in scripting examples.

**Comment by luke5542** [comment]
It looks like, as of right now, the only language missing the internal timing is Rust.

**Comment by luke5542** [comment]
@dan-c-underwood Do you think you could add the Cargo setup to get the time library added in?

**Comment by dan-c-underwood** [comment]
I'll give it a shot! Will be done as part of #8.

**Comment by luke5542** [comment]
Closed as of merge of #14
